### ISSUE TITLE
Error when running tests while dev_appserver is running

### ISSUE THREAD

**Issue by OpaVote** [Trii/NoseGAE#10]
Hello, 

It used to be the case that my tests would run fine while the dev_appserver was running (i.e., my app is being served at localhost).  Now, when dev_appserver is running, I get the error below and nose freezes so I have to kill the process.

$ nosetests -x tests/unit_tests.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/nosetests", line 8, in <module>
    load_entry_point('nose==1.1.2', 'console_scripts', 'nosetests')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/core.py", line 118, in __init__
    **extra_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/core.py", line 135, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/config.py", line 339, in configure
    self.plugins.begin()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/plugins/manager.py", line 94, in __call__
    return self.call(*arg, **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/plugins/manager.py", line 162, in simple
    result = meth(*arg, **kw)
  File "build/bdist.macosx-10.6-intel/egg/nosegae.py", line 127, in begin
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 793, in start
    self._dispatcher.start(options.api_host, apis.port, request_data)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/dispatcher.py", line 183, in start
    _module.start()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/module.py", line 1185, in start
    self._balanced_module.start()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 312, in start
    self._start_all_fixed_port(host_ports)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 349, in _start_all_fixed_port
    raise BindError('Unable to bind %s:%s' % self.bind_addr)
google.appengine.tools.devappserver2.wsgi_server.BindError: Unable to bind localhost:8080

**Comment by Trii** [comment]
Resolved via #12 and https://github.com/Trii/NoseGAE/tree/0.4.0
