### ISSUE TITLE
raise AttributeError: 'ApplicationConfiguration' object has no attribute 'modules' 

### ISSUE THREAD

**Issue by lucemia** [Trii/NoseGAE#21]
raise Exception with GAE sdk 1.9.17

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/opt/python/2.7.9/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nosegae.py", line 93, in configure
    os.environ['CURRENT_VERSION_ID'] = configuration.modules[0].version_id
AttributeError: 'ApplicationConfiguration' object has no attribute 'modules'
```

A example, this is not my project, but got the same error message. 
https://travis-ci.org/uwescience/myria-web

**Comment by sadovnychyi** [comment]
Hmm, cannot reproduce it on my machine, but I did on forked project.

The only configuration attributes available:
```
nose.plugins.nosegae: DEBUG: dir configuration: ['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_app_id', 'app_id', 'dispatch', 'servers']
```

**Comment by sadovnychyi** [comment]
https://chromium.googlesource.com/external/googleappengine/python/+/78bd635e7b42b5a8105e19b6f83aed5bbf5a6732/google/appengine/tools/devappserver2/application_configuration.py#642

The _app_id is being populated inside of __init__ as well as modules, but why they are missing with a lot of other attributes?

Expected attributes:
```
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_app_id', '_config_files_from_dir', '_config_files_from_paths', '_config_files_from_web_inf_dir', '_files_in_dir_matching', 'app_id', 'dispatch', 'modules']
```

**Comment by Trii** [comment]
Hrm, it could be yaml dependent. The ApplicationConfiguration class
populates modules based off config files inside the app dir.

I will take a look shortly when I get to the office.

**Comment by Trii** [comment]
I'm seeing strange behavior as well. I cloned https://travis-ci.org/uwescience/myria-web, build the project the way travis-ci was doing it, and then set_trace inside `nosegae.py`

```python
 89    configuration = application_configuration.ApplicationConfiguration([self._app_path])
 90    from nose.tools import set_trace; set_trace()
 91    os.environ['APPLICATION_ID'] = configuration.app_id
```

Inside a pdb session, it looks like the `ApplicationConfiguration` isn't right.
```
(Pdb) configuration._config_files_from_paths
*** AttributeError: 'ApplicationConfiguration' object has no attribute '_config_files_from_paths'
```

**Comment by Trii** [comment]
Ok. I found the issue here. I believe this package https://pypi.python.org/pypi/appengine is trying to download the *latest* google sdk from an old URL that is no longer supported. The version is 1.8.0 yet NoseGAE does not work with old, unsupported versions of the SDK. 

```
(mw-env)Josh@kapbook:myria-web$ cat /Users/Josh/Developer/Github/mw-env/google_appengine/VERSION
release: "1.8.0"
timestamp: 1367368689
api_versions: ['1']
supported_api_versions:
  python:
    api_versions: ['1']
  python27:
    api_versions: ['1']
  go:
    api_versions: ['go1']
```

**Comment by sadovnychyi** [comment]
Maybe we should prepend gae root path instead of append? It will use provided path even if its installed as a package already.

**Comment by Trii** [comment]
@sadovnychyi that is a good idea. I also need to resolve being able to pass multiple yaml / config directories to deal with modules so I can do that in a 0.5.2 release
