### ISSUE TITLE
Imports are not properly handled while running tests in parallel

### ISSUE THREAD

**Issue by sadovnychyi** [Trii/NoseGAE#34]
Given a test case:
```
import unittest
import mock

class TestTest(unittest.TestCase):
  def test_test(self):
    print dir(__import__('google'))
    with mock.patch('google.appengine.api.urlfetch.fetch'):
      pass
```

```
$ nosetests --with-gae --processes=0
Ran 1 test in 0.187s
OK
```

```
$ nosetests --with-gae --processes=1
======================================================================
ERROR: test_test (test_test.TestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sadovnychyi/example/test_test.py", line 8, in test_test
    with mock.patch('google.appengine.api.urlfetch.fetch'):
  File "/usr/local/lib/python2.7/site-packages/mock.py", line 1252, in __enter__
    self.target = self.getter()
  File "/usr/local/lib/python2.7/site-packages/mock.py", line 1414, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/local/lib/python2.7/site-packages/mock.py", line 1102, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/usr/local/lib/python2.7/site-packages/mock.py", line 1092, in _dot_lookup
    return getattr(thing, comp)
AttributeError: 'module' object has no attribute 'appengine'
-------------------- >> begin captured stdout << ---------------------
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'net']

```

I spend a lot of time trying to understand this error. Then cached that it appears only with multi process test runner. Any idea why its happening and how to fix it?

**Comment by Trii** [comment]
I think this was an issue with the sdk but I'll take a look today.

**Comment by Trii** [comment]
Oh, also print google.__file__ in the test to see if it is the sdk google or one of the other google python modules. I have seen import errors around the sdk google vs apputils (I think) that also had a top level google module.

**Comment by sadovnychyi** [comment]
I've checked the path -- its points exactly on the SDK.

**Comment by sadovnychyi** [comment]
```
print __import__('google').__file__
```

```
/Users/sadovnychyi/google-cloud-sdk/platform/google_appengine/google/__init__.pyc
```
