### ISSUE TITLE
Nosegae won't run tests with  @ndb.transactional(xg=True)

### ISSUE THREAD

**Issue by drodrigo** [Trii/NoseGAE#43]
Hello,

I'm trying to run some tests that uses NDB transactions

If a certain method has this:  @ndb.transactional() my tests will run

But if I put this  @ndb.transactional(xg=True)  this error is thrown:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock-2.0.0-py2.7.egg/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/dyego/Documents/code-stuff/mod/pdbcontest2/src/tests/core/main/test_centraldistdraw.py", line 291, in test_get_savedatastore_savePart
    draw.saveDataStore(user, pincode, [1,2,3,4,5])
  File "/home/dyego/Downloads/google_appengine/google/appengine/ext/ndb/utils.py", line 197, in inner_wrapper
    return wrapped_decorator(func, args, kwds, **options)
  File "/home/dyego/Downloads/google_appengine/google/appengine/ext/ndb/model.py", line 3834, in transactional
    func, args, kwds, **options).get_result()
  File "/home/dyego/Downloads/google_appengine/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/home/dyego/Downloads/google_appengine/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/home/dyego/Downloads/google_appengine/google/appengine/ext/ndb/context.py", line 991, in transaction
    transaction = yield parent._conn.async_begin_transaction(options, app)
  File "/home/dyego/Downloads/google_appengine/google/appengine/ext/ndb/tasklets.py", line 513, in _on_rpc_completion
    result = rpc.get_result()
  File "/home/dyego/Downloads/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/home/dyego/Downloads/google_appengine/google/appengine/datastore/datastore_rpc.py", line 2040, in __begin_transaction_hook
    self.check_rpc_success(rpc)
  File "/home/dyego/Downloads/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1373, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: transactions on multiple entity groups only allowed with the High Replication datastore
```

Is there a way to simply ignore this?

Thanks

**Comment by sadovnychyi** [comment]
https://cloud.google.com/appengine/docs/python/tools/localunittesting#Python_Writing_High_Replication_Datastore_tests

**Comment by drodrigo** [comment]
Oh thanks a lot! 

I should have simply googled "high replication tests python", silly me....

Sorry for this, I'm closing this "issue"

**Comment by drodrigo** [comment]
Oh thanks a lot!

I should have simply googled "high replication tests python", silly me....

Sorry for this, I'm closing this "issue"
